---
homeassistant:
  name: Eindhoven
  latitude: 51.479751
  longitude: 5.503628
  elevation: 0
  unit_system: metric
  currency: EUR
  country: NL
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  allowlist_external_dirs:
    - "/tmp"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.73
    - type: homeassistant

logger:
  default: info
  # logs:
  #  homeassistant.components.webhook: debug
  #  homeassistant.components.config: debug
  #  homeassistant.components.config.automation: debug
  #  homeassistant.components.sensor.rest: debug
  #  homeassistant.components.rfxtrx: debug
  #  homeassistant.components.mqtt: debug

#
# END MAIN CONFIG - START OTHER CONFIG #
#

cloud:
config:
conversation:

energy:

frontend:
  themes:
    solarized_dark: !include themes/solarized_dark.yaml

history:

logbook:
map:
mobile_app:

python_script:

recorder:
  purge_keep_days: 30
  db_url: sqlite:////config/home-assistant_v2.db

shopping_list:

sun:
system_health:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

tts:
  - platform: google_translate

#
# END OTHER CONFIG - START INCLUDES #
#

binary_sensor: !include devices/binary_sensor.yaml
device_tracker: !include devices/device_tracker.yaml
climate: !include devices/climate.yaml
homekit: !include devices/homekit.yaml
input_select: !include devices/input_select.yaml
input_boolean: !include devices/input_boolean.yaml
input_number: !include devices/input_number.yaml
input_datetime: !include devices/input_datetime.yaml
light: !include devices/light.yaml
notify: !include devices/notify.yaml
rest_command: !include devices/rest_command.yaml
schedule: !include devices/schedule.yaml
sensor: !include devices/sensor.yaml
shell_command: !include devices/shell_command.yaml
sql: !include devices/sql.yaml
switch: !include devices/switch.yaml
utility_meter: !include devices/utility_meter.yaml

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
