---
- alias: "Actual lamp for wakeup Emma"
  trigger:
    - platform: state
      entity_id: schedule.emma_wakeup_schedule
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'off'
  action:
    - service: hue.activate_scene
      target:
        entity_id:
          - scene.emma_wakeup

- alias: "Actual lamp for wakeup Emma - holiday"
  trigger:
    - platform: time
      at: "07:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.is_it_holiday
      state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id:
          - scene.emma_wakeup

- alias: "Actual lamp for wakeup Emma - turn off"
  trigger:
    - platform: state
      entity_id: schedule.emma_wakeup_schedule
      to: 'off'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.h_emma
          - light.h_play_emma
