# temporary roofpump
- alias: 'timer_temporary_roofpump'
  trigger:
    platform: time_pattern
    minutes: 0
  condition:
    - condition: numeric_state
      entity_id: sensor.openweathermap_rain
      above: 0.0
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.shellyplug_s_20e7b0
    - service: notify.pushover
      data_template:
        title: "Dakpomp"
        message: "Dakpomp aan omdat regenval {{ states.sensor.openweathermap_rain.state }}mm is."
    - delay: '00:05:00'
    - service: switch.turn_off
      target:
        entity_id: switch.shellyplug_s_20e7b0
    - service: notify.pushover
      data_template:
        title: "Dakpomp"
        message: "Dakpomp uit."

