---
# stop tesla charger
- alias: turn off tesla charger
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == states('input_datetime.stop_tesla_charger')[0:5] }}"
  condition:
    - condition: state
      entity_id: input_boolean.stop_tesla_charger
      state: 'on'
    - condition: state
      entity_id: switch.tesla_kevin_charger_switch
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.tesla_kevin_charger_switch
    - service: input_boolean.turn_off
      entity_id: input_boolean.stop_tesla_charger
