---
- alias: Event doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
    - platform: state
      entity_id: input_boolean.fake_doorbell
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.street
      data:
        filename: "/tmp/eventdoorbell1.jpg"
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/eventdoorbell2.jpg"
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: -2
          attachment: "/tmp/eventdoorbell1.jpg"
    - service: notify.pushover
      data:
        title: "Deurbel"
        message: "De deurbel gaat"
        data:
          priority: 0
          attachment: "/tmp/eventdoorbell2.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "Deurbel gaat"
    - service: script.sonos_dingdong
      data_template:
        sonos_entity: media_player.sonos_keuken
        volume: "{{ states('input_number.doorbell_volume') }}"
    - service: script.sonos_dingdong
      data_template:
        sonos_entity: media_player.sonos_badkamer
        volume: "{{ states('input_number.doorbell_volume') }}"
    - service: input_boolean.turn_off
      entity_id: input_boolean.fake_doorbell
    - delay: 120
    - service: notify.telegram
      data:
        message: ''
        data:
          video:
            - url: "{{ state_attr('camera.front_door', 'video_url') }}"
              caption: "Video van laatste bezoek"


- alias: Send ring video
  trigger:
    - platform: state
      entity_id: input_boolean.send_ring_video
      to: 'on'
  action:
    - service: notify.telegram
      data:
        message: ''
        data:
          video:
            - url: "{{ state_attr('camera.front_door', 'video_url') }}"
              caption: "Video van laatste bezoek"
    - service: input_boolean.turn_off
      entity_id: input_boolean.send_ring_video

- alias: Plex pause doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.atv_living_room
      state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.atv_living_room

- alias: TV mute doorbell
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      to: 'on'
  condition:
    - condition: template
      value_template:
        '{{states.remote.living_room.attributes.current_activity == "TV" }}'
  action:
    - service: remote.send_command
      data:
        entity_id: remote.living_room
        device: 42809894 # Entone
        command:
          - Pause
