---
- alias: Emma Sonos button 1 press
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: on_press
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.sonos_emma
          state: playing
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_emma
      data:
        volume_level: .1
    - service: media_player.select_source
      entity_id: media_player.sonos_emma
      data:
        source: 'Juf Roos'  # favorite playlist
    - service: media_player.shuffle_set
      entity_id: media_player.sonos_emma
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.sonos_emma

- alias: Emma Sonos button 2 press
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: up_press
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.sonos_emma
          state: playing
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_emma
      data:
        volume_level: .1
    - service: media_player.select_source
      entity_id: media_player.sonos_emma
      data:
        source: 'Minidisco'  # favorite playlist
    - service: media_player.shuffle_set
      entity_id: media_player.sonos_emma
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.sonos_emma

- alias: Emma Sonos button 3 press
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: down_press
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.sonos_emma
          state: playing
  action:
    - service: media_player.volume_set
      entity_id:
        - media_player.sonos_emma
      data:
        volume_level: .1
    - service: media_player.select_source
      entity_id: media_player.sonos_emma
      data:
        source: 'Dirk Scheele'  # favorite playlist
    - service: media_player.shuffle_set
      entity_id: media_player.sonos_emma
      data:
        shuffle: true
    - service: media_player.media_next_track
      entity_id: media_player.sonos_emma

- alias: Emma Sonos button 4 press
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: off_press
  condition:
    - condition: state
      entity_id: media_player.sonos_emma
      state: playing
  action:
    - service: media_player.media_pause
      entity_id: media_player.sonos_emma

- alias: Emma Sonos button 1 2 3 press - next
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: on_press
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: up_press
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:17:88:01:0d:8a:7e:5c'
        command: down_press
  condition:
    - condition: state
      entity_id: media_player.sonos_emma
      state: playing
  action:
    - service: media_player.media_next_track
      entity_id: media_player.sonos_emma
