---
- alias: update_battery_template_sensors
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 0
  action:
    - service: homeassistant.update_entity
      entity_id:
        - sensor.long_time_not_seen_devices
        - sensor.short_time_not_seen_devices

- alias: send_long_time_battery_devices_notification
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: template
    value_template: >
      {% if (states.sensor.long_time_not_seen_devices.state != '') %}
        true
      {% else %}
        false
      {% endif %}
  action:
    - service: notify.pushover
      data:
        title: "Sensor batterijen (lang)"
        message: "{{ states.sensor.long_time_not_seen_devices.state }}"

- alias: send_short_time_battery_devices_notification
  trigger:
    platform: time_pattern
    minutes: '/30'
    seconds: 0
  condition:
    - condition: template
      value_template: >
        {% if (states.sensor.short_time_not_seen_devices.state != '') %}
          true
        {% else %}
          false
        {% endif %}
    - condition: state
      entity_id: input_boolean.someone_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.is_it_night
      state: 'off'
  action:
    - service: notify.pushover
      data:
        title: "Sensor batterijen (kort)"
        message: "{{ states.sensor.short_time_not_seen_devices.state }}"

- alias: ring_battery_below_treshold
  trigger:
    platform: numeric_state
    entity_id: sensor.front_door_battery
    below: 21
  action:
    - service: notify.pushover
      data:
        title: "Ring batterij leeg"
        message: "Batterij van de deurbel bijna leeg (20%), graag vervangen."
