---
- alias: Car insurance expiration
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.liability_insured
        - binary_sensor.liability_insured_2
      to: 'on'
  action:
    - service: notify.pushover
      data_template:
        title: "Verzekering"
        message: "Verzekering van een auto verlopen."

- alias: APK upcoming Tesla
  trigger:
    - platform: time
      at: 20:00
  conditions:
    - condition: numeric_state
      entity_id: sensor.apk_expiration
      below: 1
      value_template: "{{ (as_timestamp(states.sensor.apk_expiration.state) - (as_timestamp(now() + timedelta(days=532)))) / (3600 * 24) }}"
  action:
    - service: notify.pushover
      data_template:
        title: "APK"
        message: "APK van Tesla Model 3 verloopt binnen 30 dagen."

- alias: APK upcoming Kia
  trigger:
    - platform: time
      at: 20:00
  conditions:
    - condition: numeric_state
      entity_id: sensor.apk_expiration_2
      below: 1
      value_template: "{{ (as_timestamp(states.sensor.apk_expiration.state) - (as_timestamp(now() + timedelta(days=30)))) / (3600 * 24) }}"
  action:
    - service: notify.pushover
      data_template:
        title: "APK"
        message: "APK van Kia Picanto verloopt binnen 30 dagen."
