---
- alias: Front door opens
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_frontdoor_door_window
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/frontdooropens.jpg"
    - service: notify.pushover
      data:
        title: "Voordeur geopend"
        message: "De voordeur is geopend"
        data:
          priority: -2
          attachment: "/tmp/frontdooropens.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "De voordeur is geopend"

- alias: Front door motion
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.tts_test
      to: 'on'
  action:
    - service: camera.snapshot
      entity_id: camera.frontdoor
      data:
        filename: "/tmp/frontdoormotion.jpg"
    - service: notify.pushover
      data:
        title: "Persoon bij de voordeur"
        message: "Er is een persoon bij de voordeur gedetecteerd"
        data:
          attachment: "/tmp/frontdoormotion.jpg"
    - service: notify.telegram
      data:
        message: ''
        data:
          photo:
            - url: !secret camera2_still
              caption: "Persoon bij de voordeur"
    - service: input_boolean.turn_off
      entity_id: input_boolean.tts_test

- alias: Front door motion carport light
  trigger:
    - platform: state
      entity_id: binary_sensor.shelly_door_frontdoor_door_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_motion
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.is_it_night
        state: 'on'
      - condition: state
        entity_id: light.h_carport
        state: 'on'
  action:
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_evening
    - delay: "00:01"
    - service: hue.activate_scene
      target:
        entity_id: scene.voortuin_dom_night

- alias: Garage motion
  trigger:
    - platform: event
      event_type: nest_event
      event_data:
        device_id: !secret nest_cam_outdoor_id
        type: person_detected
  action:
    - service: notify.pushover
      data_template:
        title: "Beweging in de garage"
        message: "Er is beweging in de garage/achtertuin"
        data:
          file:
            url: "{{ 'http://' + states.sensor.internal_ip_lan.state + ':8123' + states.camera.outdoor.attributes.entity_picture }}"
    - service: notify.telegram
      data_template:
        message: ''
        data:
          photo:
            - url: "{{ 'http://' + states.sensor.internal_ip_lan.state + ':8123' + states.camera.outdoor.attributes.entity_picture }}"
              caption: "Beweging gedetecteerd achtertuin/garage"

- alias: Emma sound
  trigger:
    - platform: event
      event_type: nest_event
      event_data:
        device_id: !secret nest_cam_emma_id
        type: camera_sound
  action:
    - service: notify.pushover
      data_template:
        title: "Geluid op kamer Emma"
        message: "Er is geluid op de kamer van Emma"
        data:
          file:
            url: "{{ 'http://' + states.sensor.internal_ip_lan.state + ':8123' + states.camera.emma.attributes.entity_picture }}"
    - service: notify.telegram
      data_template:
        message: ''
        data:
          photo:
            - url: "{{ 'http://' + states.sensor.internal_ip_lan.state + ':8123' + states.camera.emma.attributes.entity_picture }}"
              caption: "Geluid op kamer Emma"
