---
- alias: P2000 Notify
  trigger:
    platform: state
    entity_id: sensor.p2000_eindhoven
  action:
    - service_template: notify.pushover
      data_template:
        title: "P2000 bericht"
        message: "{{ states.sensor.p2000_eindhoven.state + states.sensor.p2000_eindhoven.attributes.capcode }}"
        data:
          priority: 0
