---
- alias: PiHole update
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.pi_hole_core_update_available
        - binary_sensor.pi_hole_ftl_update_available
        - binary_sensor.pi_hole_web_update_available
      to: 'on'
  action:
    - service: notify.pushover
      data_template:
        title: "PiHole update beschikbaar"
        message: "{{ trigger.entity_id }}"

