---
- alias: Weather morning notification
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Weerbericht"
        message: "Het wordt vandaag
          min. {{ states.sensor.today_templow.state | round(0) }} en
          max. {{ states.sensor.today_temphigh.state | round(0) }} graden.
          Het is nu {{ states.sensor.pirateweather_temperature.state | round(0) }}
          graden."

- alias: Weather evening notification
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service_template: notify.pushover
      data_template:
        title: "Weerbericht"
        message: "Het wordt morgen
          min. {{ states.sensor.tomorrow_templow.state | round(0) }} en
          max. {{ states.sensor.tomorrow_temphigh.state | round(0) }} graden."
