---
- platform: template
  sensors:
    pir_hal:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_554555', 'on') }}"
    pir_kantoor:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_1ee0e9', 'on') }}"
    pir_keuken:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_2891e9', 'on') }}"
    pir_cvruimte:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_e94fe9', 'on') }}"
    pir_woonkamer:
      device_class: motion
      value_template: "{{ is_state('binary_sensor.pt2262_8cefa9', 'on') }}"
    brandalarm_woonkamer:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_791400_32', 'on') }}"
    brandalarm_keuken:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_4c4000_32', 'on') }}"
    brandalarm_zolder:
      device_class: smoke
      value_template: "{{ is_state('binary_sensor.kd101_smoke_detector_d48600_32', 'on') }}"
      #    deurbel:
      #      device_class: door
      #      value_template: "{{ is_state('input_boolean.deurbel', 'on') }}"
