---
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: command_line
  name: CPU Temperatuur
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_free
    - type: load_5m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: processor_use
    - type: last_boot
- platform: command_line
  name: Internal IP LAN
  command: "ip addr show eth0 | grep -Po 'inet \\K[\\d.]+'"
- platform: command_line
  name: External IP
  command: "/usr/bin/curl -s kvanhoorn.nl/myip/"
- platform: command_line
  name: Database size
  command: 'ls -hl /config/home-assistant_v2.db | tr -s " " | /usr/bin/cut -d " " -f5'
- platform: darksky
  api_key: 2cbc3be161a2e13481e8c56cf491c525
  forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - visibility
    - temperature_high
    - temperature_low
    - uv_index
- platform: feedparser
  name: Omroep Brabant Zuid-Oost
  url: !secret omroepbrabant_rss_url
  attributes:
    - summary
    - link
- platform: feedparser
  name: NOS Algemeen
  url: !secret nosalgemeen_rss_url
  attributes:
    - link
- platform: feedparser
  name: nu.nl Algemeen
  url: !secret nunlalgemeen_rss_url
  attributes:
    - link
    - summary
- platform: template
  sensors:
    temperatuur_kantoor:
      friendly_name: 'Kantoor'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.tfa_ts34c_cresta_3e_0e_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.tfa_ts34c_cresta_3e_0e_humidity.state }}"
        battery: "{{ states.sensor.tfa_ts34c_cresta_3e_0e_battery_numeric.state }}"
    temperatuur_slaapkamer:
      friendly_name: 'Slaapkamer'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.tfa_ts34c_cresta_5c_0e_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.tfa_ts34c_cresta_5c_0e_humidity.state }}"
        battery: "{{ states.sensor.tfa_ts34c_cresta_5c_0e_battery_numeric.state }}"
    temperatuur_garage:
      friendly_name: 'Garage'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.tfa_ts34c_cresta_53_0e_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.tfa_ts34c_cresta_53_0e_humidity.state }}"
        battery: "{{ states.sensor.tfa_ts34c_cresta_53_0e_battery_numeric.state }}"
    temperatuur_wc:
      friendly_name: 'WC'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.tfa_ts34c_cresta_7c_0e_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.tfa_ts34c_cresta_7c_0e_humidity.state }}"
        battery: "{{ states.sensor.tfa_ts34c_cresta_7c_0e_battery_numeric.state }}"
    temperatuur_buiten:
      friendly_name: 'Buiten'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.rtgr328_bf_01_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.rtgr328_bf_01_humidity.state }}"
        battery: "{{ states.sensor.rtgr328_bf_01_battery_numeric.state }}"
    plant1:
      friendly_name: 'Peace Lily - witte bloem'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.imagintronix_00_01_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.imagintronix_00_01_humidity.state }}"
        battery: "{{ states.sensor.imagintronix_00_01_battery_numeric.state }}"
    plant2:
      friendly_name: 'Yucca - palmboom'
      unit_of_measurement: '°C'
      icon_template: 'mdi:thermometer'
      value_template: "{{ states.sensor.imagintronix_00_02_temperature.state }}"
      attribute_templates:
        humidity: "{{ states.sensor.imagintronix_00_02_humidity.state }}"
        battery: "{{ states.sensor.imagintronix_00_02_battery_numeric.state }}"
    plant1_humidity:
      friendly_name: 'Peace Lily - witte bloem (humidity)'
      unit_of_measurement: '%'
      icon_template: 'mdi:water'
      value_template: "{{ states.sensor.imagintronix_00_01_humidity.state }}"
    plant2_humidity:
      friendly_name: 'Yucca - palmboom (humidity)'
      unit_of_measurement: '%'
      icon_template: 'mdi:water'
      value_template: "{{ states.sensor.imagintronix_00_02_humidity.state }}"
    livingroom_temperature:
      value_template: "{{states.climate.anna.attributes.current_temperature}}"
      friendly_name: 'Woonkamer'
      unit_of_measurement: '°C'
    long_time_not_seen_devices:
      friendly_name: 'Meer dan 3 dagen niet gezien'
      icon_template: 'mdi:battery'
      value_template: >
        {% for entity in (states | selectattr('entity_id','in', state_attr('group.long_battery_devices','entity_id'))) %}
          {%- if (as_timestamp(now()) - as_timestamp(entity.last_updated) > (60 * 60 * 24 * 3)) -%}
            {{ entity.name }},
          {%- endif -%}
        {% endfor %}
    short_time_not_seen_devices:
      friendly_name: 'Meer dan 6 uur niet gezien'
      icon_template: 'mdi:battery'
      value_template: >
        {% for entity in (states | selectattr('entity_id','in', state_attr('group.short_battery_devices','entity_id'))) %}
          {%- if (as_timestamp(now()) - as_timestamp(entity.last_updated) > (60 * 60 * 6)) -%}
            {{ entity.name }},
          {%- endif -%}
        {% endfor %}
    bedroom_vs_outside_temperature:
      friendly_name: 'Slaapkamer vs buiten temperatuur'
      icon_template: 'mdi:temperature-celsius'
      unit_of_measurement: '°C'
      value_template: >
        {{ (states.sensor.temperatuur_slaapkamer.state | float -
        states.sensor.hm_backyard_temperature.state | float) |
        float | round(2) }}
    living_vs_outside_temperature:
      friendly_name: 'Woonkamer vs buiten temperatuur'
      icon_template: 'mdi:temperature-celsius'
      unit_of_measurement: '°C'
      value_template: >
        {{ (states.climate.anna.attributes.current_temperature | float -
        states.sensor.hm_backyard_temperature.state | float) |
        float | round(2) }}
    untappd_full_checkin:
      friendly_name: Untappd last checkin full
      #entity_id: sensor.untappd_last_check_in_kvanhoorn
      value_template: >
        {{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.brewery }} -
        {{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.beer }}
        ({{ states.sensor.untappd_last_check_in_kvanhoorn.attributes.abv }})
    next_setting:
      friendly_name: Zonsondergang
      #entity_id: sun.sun
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') }}
    next_rising:
      friendly_name: Zonsopgang
      #entity_id: sun.sun
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') }}
    daily_power:
      friendly_name: Daily Power
      device_class: energy
      unit_of_measurement: kWh
      value_template: >
        {% if is_number(states('sensor.daily_power_offpeak')) and
           is_number(states('sensor.daily_power_peak')) %}
           {{ states('sensor.daily_power_offpeak') | float +
              states('sensor.daily_power_peak') | float }}
        {% else %}
           None
        {% endif %}
    monthly_power:
      friendly_name: Monthly Power
      device_class: energy
      unit_of_measurement: kWh
      value_template: >
        {% if is_number(states('sensor.monthly_power_offpeak')) and
           is_number(states('sensor.monthly_power_peak')) %}
           {{ states('sensor.monthly_power_offpeak') | float +
              states('sensor.monthly_power_peak') | float }}
        {% else %}
           None
        {% endif %}
    roborock_s5_max_filter_left_hours:
      friendly_name: Roborock S5 Max Filter Left Hours
      icon_template: 'mdi:air-filter'
      unit_of_measurement: hours
      value_template: "{{ (states('sensor.roborock_s5_max_filter_left') | int / (60 * 60)) | int }}"
    roborock_s5_max_main_brush_left_hours:
      friendly_name: Roborock S5 Max Main Brush Left Hours
      icon_template: 'mdi:brush'
      unit_of_measurement: hours
      value_template: "{{ (states('sensor.roborock_s5_max_main_brush_left') | int / (60 * 60)) | int }}"
    roborock_s5_max_side_brush_left_hours:
      friendly_name: Roborock S5 Max Side Brush Left Hours
      icon_template: 'mdi:brush'
      unit_of_measurement: hours
      value_template: "{{ (states('sensor.roborock_s5_max_main_brush_left') | int / (60 * 60)) | int }}"
    roborock_s5_max_sensor_dirty_left_hours:
      friendly_name: Roborock S5 Max Sensor Dirty Left Hours
      icon_template: 'mdi:eye-outline'
      unit_of_measurement: hours
      value_template: "{{ (states('sensor.roborock_s5_max_sensor_dirty_left') | int / (60 * 60)) | int }}"
    daily_cost_power_round:
      friendly_name: Daily Cost of power usage rounded at 2 decimals
      icon_template: 'mdi:flash'
      unit_of_measurement: '€'
      value_template: "{{ (states('sensor.energy_consumption_tarif_1_cost') | float + states('sensor.energy_consumption_tarif_2_cost') | float) | round(2) }}"
    daily_cost_gas_round:
      friendly_name: Daily Cost of gas usage rounded at 2 decimals
      icon_template: 'mdi:fire'
      unit_of_measurement: '€'
      value_template: "{{ states('sensor.gas_consumption_cost') | round(2) }}"
    daily_cost_water_round:
      friendly_name: Daily Cost of water usage rounded at 2 decimals
      icon_template: 'mdi:water'
      unit_of_measurement: '€'
      value_template: "{{ states('sensor.watermeter_3c39e72f95de_total_water_usage_cost') | round(2) }}"
- platform: scrape
  name: Euro95
  resource: !secret fuel_prices_nationwide
  select: ".table .table-row:nth-of-type(2) div:nth-of-type(3)"
  value_template: "{{ value.split(' ')[1].replace(',', '.') | float }}"
  scan_interval: 3600
- platform: scrape
  name: Diesel
  resource: !secret fuel_prices_nationwide
  select: ".table .table-row:nth-of-type(3) div:nth-of-type(3)"
  value_template: "{{ value.split(' ')[1].replace(',', '.') | float }}"
  scan_interval: 3600
- platform: ovapi
  name: Bus 4
  timing_point_code: !secret busstop_code
  show_future_departures: 2
- platform: untappd
  username: kvanhoorn
  id: !secret untappd_id
  secret: !secret untappd_secret
- platform: postcodeloterij
  postcode: !secret postcode
- platform: afvalwijzer
  provider: mijnafvalwijzer
  postal_code: !secret postcode
  street_number: !secret housenumber
  include_date_today: true
- platform: p2000
  scan_interval: 10
  name: P2000 Eindhoven
  regios: 22
  radius: 2000
- platform: easyenergy
  gas_decimals: 5
  power_decimals: 5
- platform: easyenergy
  timedelta: 1
- platform: cleanprofs
  postalcode: !secret postcode
  housenumber: !secret housenumber
