---
- platform: time_date
  display_options:
    - 'time'
    - 'date'
- platform: feedparser
  name: Omroep Brabant Zuid-Oost
  url: !secret omroepbrabant_rss_url
  attributes:
    - summary
    - link
- platform: feedparser
  name: NOS Algemeen
  url: !secret nosalgemeen_rss_url
  attributes:
    - link
- platform: feedparser
  name: nu.nl Algemeen
  url: !secret nunlalgemeen_rss_url
  attributes:
    - link
    - summary
- platform: ovapi
  name: Bus 4
  timing_point_code: !secret busstop_code
  show_future_departures: 2
- platform: untappd
  username: kvanhoorn
  id: !secret untappd_id
  secret: !secret untappd_secret
- platform: postcodeloterij
  postcode: !secret postcode
- platform: afvalwijzer
  provider: mijnafvalwijzer
  postal_code: !secret postcode
  street_number: !secret housenumber
  include_date_today: true
- platform: p2000
  scan_interval: 10
  name: P2000 Eindhoven
  regios: 22
  radius: 2000
