---
- platform: template
  switches:
    livingroom_lighting:
      value_template: "{{ states.light.h_piano.state == 'on'
        and states.light.h_schemerlamp.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Zitkamer"
          scene_name: "DOM_evening"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_schemerlamp
            - light.h_staande_lamp
            - light.h_tv_lamp
            - light.h_piano
            - light.h_tv_play_left
            - light.h_tv_play_right
    diningtable_lighting:
      value_template: "{{ states.light.h_tafel_kamer.state == 'on'
        and states.light.h_tafel_raam.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Eettafel"
          scene_name: "DOM_default"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_tafel_kamer
            - light.h_tafel_raam
    outdoor_lighting:
      value_template: "{{ states.light.h_outdoor_1.state == 'on' 
        and states.light.h_outdoor_4.state == 'on' }}"
      turn_on:
        service: hue.hue_activate_scene
        data:
          group_name: "Achtertuin"
          scene_name: "DOM_outdoor_evening"
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_outdoor_1
            - light.h_outdoor_2
            - light.h_outdoor_3
            - light.h_outdoor_4
            - light.h_outdoor_5
            - light.h_outdoor_6
            - light.h_outdoor_7
    bathroom_lighting:
      value_template: "{{ states.light.h_badkamer_links.state == 'on'
        and states.light.h_badkamer_rechts.state == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.h_badkamer_links
            - light.h_badkamer_midden
            - light.h_badkamer_rechts
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_badkamer_links
            - light.h_badkamer_midden
            - light.h_badkamer_rechts
    atticfront_lighting:
      value_template: "{{ states.light.h_zolder_voor_deur == 'on'
        and states.light.h_zolder_voor_muur == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.h_zolder_voor_deur
            - light.h_zolder_voor_muur
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_zolder_voor_deur
            - light.h_zolder_voor_muur
    atticback_lighting:
      value_template: "{{ states.light.h_zolder_achter_deur == 'on'
        and states.light.h_zolder_achter_muur == 'on' }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id:
            - light.h_zolder_achter_deur
            - light.h_zolder_achter_muur
      turn_off:
        service: light.turn_off
        data:
          entity_id:
            - light.h_zolder_achter_deur
            - light.h_zolder_achter_muur
    office_music_sonos:
      friendly_name: Kantoormuziek
      value_template: "{{ states.media_player.sonos_kantoor.state == 'playing' }}"
      turn_on:
        - service: media_player.volume_set
          entity_id:
            - media_player.sonos_kantoor
          data:
            volume_level: .2
        - service: media_player.play_media
          target:
            entity_id: media_player.sonos_kantoor
          data:
            media_content_type: "favorite_item_id"
            media_content_id: "FV:2/18" # Kantoor favorite
        - service: media_player.shuffle_set
          entity_id: media_player.sonos_kantoor
          data:
            shuffle: true
        - service: media_player.media_next_track
          entity_id: media_player.sonos_kantoor
      turn_off:
        - service: media_player.media_pause
          target:
            entity_id: media_player.sonos_kantoor

#- platform: mqtt
#  name: Sous vide
#  state_topic: anova/timer
#  command_topic: anova/command/timer_run
#  payload_on: 'running'
#  payload_off: 'stopped'
#  state_on: 'running'
#  state_off: 'stopped'
#  optimistic: false
#  retain: true
#  value_template: "{{ value_json.timer_state }}"
#  icon: 'mdi:timer'
