---
- alias: Fire alarm
  trigger:
    platform: state
    entity_id:
      - binary_sensor.rookmelder_woonkamer_smoke
      - binary_sensor.rookmelder_keuken_smoke
      - binary_sensor.rookmelder_zolder_smoke
    to: 'on'
  action:
    - service: notify.pushover
      data_template:
        message: "Er is brand gemeld door
          {{trigger.to_state.attributes.friendly_name}}"
        title: "Brandalarm"
        data:
          sound: "siren"
          priority: 2
          expire: 3600
          retry: 60
